### ISSUE TITLE
Create jupyter notebook to assist with reviewing matches

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#11]
I'm not entirely familiar with all the things 'UI' elements a  jupyter notebook supports - seems to be some support through ipywidgets. I'm imagining something like the following:

User points the notebook to the results CSV they wish to review.

The notebook loads the report into an array sorted by most similar to least similar. 

The interface then displays one match at a time as follows:
* the filenames and similarity metric
* both videos side by side in an interactive player
* the 'filmstrip' visualization we've used in template matching 

The user can then click to see the next/previous match

**Comment by fsbatista** [comment]
- Query v Match (one at a time)
- Show i of len(match)
- Next and previous (for both matches and queries)
