### ISSUE TITLE
Allow/Document running template matching as a script

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#13]
As discussed in #11, once we move template location information to the config.yaml file - we should allow a user to run a script to process all of their templates across all of their videos.

The output of this script should take our standard csv/metadata/database approach, and include the following infomation:

* video filename
* sha-1 of video
* template name (from directory name)
* distance
* timestamp for highly correlated frames (let me know what we have for this info)

**Comment by fsbatista** [comment]
cbd62b9
