### ISSUE TITLE
Investigate possible issue with API endpoints missing videos in sud directories

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#144]
My steps:
* Before I did my processing, i added .flv and .mkv extensions to my config.yaml

* Files were processed sucessfully

* I confirm the database contains what i see as appropriate paths for these in files.file_path of the form "baggio_penalty_1994/37b31d607d31a47d347b15dae2b8aa63e57861eb.flv"

* I confirm the videos are actually located in the mounted directory on the server container

Result:
* videos in the root folder play fine
* videos in sub folders render a card
* they do not play successfully but the /watch endpoint doesnt 404/502 or anything

**Comment by stepan-anokhin** [comment]
The root cause is that `flv` support is disabled by default by the [react-player](https://www.npmjs.com/package/react-player#config-prop) (or it cannot automatically detect that the file is flv).
