### ISSUE TITLE
Fix annotation notebook to pull directory from config.yaml

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#15]
Currently the annotation notebook has a hard coded value for where it looks for the representations. This should adapt to the value from config.yaml by default.

Additionally, the location of the matches csv should also default to the location from config.yaml

**Comment by fsbatista** [comment]
Added the option of running the notebook with the defaults being pulled from the config file or just a manual path ( [commit 1](https://github.com/benetech/VideoDeduplication/commit/129b129bea9f97c5715ac05d07c8f4e1fee2af9a) and [commit 2](https://github.com/benetech/VideoDeduplication/commit/11f7def0fd15cdf0db5b3296936469b221c25905)
