### ISSUE TITLE
Fix data folder mounting missmatch.

### ISSUE THREAD

**Issue by stepan-anokhin** [benetech/VideoDeduplication#153]
Currently `make run` command rely on the `BENETECH_DATA_LOCATION` environment variable (usually generated and stored in the `.env` file). But `dedup` container by default expects video-folder to be a `test_dataset` subfolder of the mounted `BENETECH_DATA_LOCATION` directory, while `server` container expects video-folder to be at `BENETECH_DATA_LOCATION` root. This missmatch must be fixed.

**Comment by johnhbenetech** [comment]
@fsbatista I think we should get rid of test_dataset across the board, what do you think?

I think now with the various listo of file and subfolder processing improvements we can just assume /data is where everything can start

**Comment by fsbatista** [comment]
Do you mean getting rid of it and then parameterizing at runtime in order to show where within data/ it should look for files?

**Comment by johnhbenetech** [comment]
@fsbatista Just assume whatever the user provides during 'make run' will be the mount point. If a user doesn't want to process all media within the mount point they can use the list of files option.

Basically, we would remove the /test_dataset reference from the config.yml and that way both dedup and server agree on the same mountpoint (/data) and all paths relative to that mountpoint

**Comment by stepan-anokhin** [comment]
The problem here is the following:
* we use the same variable `BENETECH_DATA_LOCATION` to mount user videos into `dedup` and `server` container. 
* by default the `config.yaml:sources.root` points to the `test_dataset` subfolder of the mounted folder (my understanding is that it just happened like this historically).
* by default `server` expects videos to be in the root folder of the mounted folder (the assuption was that the user will not wish to reveal unneeded extra folders to the application). 


Whatever approach we choose we need to make sure that 
* the same directory must have exactly the same meaning in all containers it is mounted. 
* the default settings must work out of the box.
* settings should be as simple as possible, and follow the least surprise principle

So what @johnhbenetech proposes makes total sense to me. Namely:
1. There should be single data folder (specified in the `BENETECH_DATA_LOCATION` variable in shell or in the `.env` file) which is mounted to all containers. 
1. By default we assume that this is a root folder in which all the data is located
1. All file paths in database and csv output files are relative to that folder.
1. `config.yaml: source.root` must points to that folder's mount point in `dedup-app` container.
1. `VIDEO_FOLDER` variable must point to that folder's mount point in `server` container.

**Comment by stepan-anokhin** [comment]
Also it makes sense to allow to override `config.yaml` settings with environment variables. In this case we will be able to change settings (like database uri) entirely in `docker-compose.yaml`.
