### ISSUE TITLE
Investigate intermittent failure to load matches

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#166]
Not really sure of the exact cause (no consistent failed network requests or JS console logs).

Steps to reproduce:
* Quickly click through to a single video view (one with matches so maybe sort by match count)

* On load quickly click to the matches tab

Result:
Although the match count is rendered accurately, the match cards do not render. If a user reloads the page (or goes back to dashboard and reclicks) the matches load correctly.

If you cant reproduce try going back and forth to dashboard and clicking several different videos until it happens.

It feels like some sort of simultaneous request blocking or DOM race condition or something. Not sure

**Comment by stepan-anokhin** [comment]
The issue is reproducible in my environment.

**Comment by stepan-anokhin** [comment]
![2020-10-28-135345_1920x1054_scrot](https://user-images.githubusercontent.com/38860530/97402662-7f96b680-1925-11eb-8acb-fcefdfb84707.png)

Matches are loaded correctly, but filters contain invalid file id (see highlighted id missmatch in URL and redux state).
