### ISSUE TITLE
Generate matches error

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#17]
However, I had the following error in the second step to generate matches while running the 14k set:

Finding Matches...
Generating Report
Saving unfiltered report to /datadrive/outputs/representations1/matches_at_0.5_distance.csv
Filtering dark and/or short videos
Traceback (most recent call last):
  File "generate_matches.py", line 149, in <module>
    video_length = np.array(frame_level_data)[:,0]
IndexError: too many indices for array

I guess it has something to do with the size of the set. The main csv looks OK, I'm only missing the filtered and the signatures files.

**Comment by fsbatista** [comment]
I'll add some error handling (I think this is related to not finding the source files or something like that)
