### ISSUE TITLE
allow for mkv playback in Firefox

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#206]
mkv playback works in Chrome but not firefox. the error message is:

HTTP “Content-Type” of “video/x-matroska” is not supported. Load of media resource https://justiceai.tech/api/v1/files/1/watch failed.

you can see example: https://justiceai.tech/collection/fingerprints/1

**Comment by stepan-anokhin** [comment]
Unfortunately this is not supported. Please see the corredponding feature request: [Support mkv|matroska|video/x-matroska in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891)

The only way to accomplish something like that is by using add-ons like the following:
* [Open in VLC media player](https://addons.mozilla.org/en-US/firefox/addon/open-in-vlc)
* Or [Send to MPV player](https://addons.mozilla.org/en-US/firefox/addon/send-to-mpv-player)
