### ISSUE TITLE
Make run fails for GPU environment

### ISSUE THREAD

**Issue by fsbatista** [benetech/VideoDeduplication#211]
When running make run after choosing the option of building the image locally I get the following error:

ERROR: Cannot locate specified Dockerfile: docker/Dockerfile.dedup-GPU
.mk/docker.mk:19: recipe for target 'docker-run' failed
make: *** [docker-run] Error 1

The GPU section of the filename is in caps and is different from the filename. I think it's sourced directly from the ENV file. Changing the name of the docker compose file solves it but I'm not sure if there are other implications.

**Comment by stepan-anokhin** [comment]
@fsbatista Cannot reproduce. Could you please run `make setup-update` and check again? It looks like your `.env` file should be updated.

**Comment by fsbatista** [comment]
setup-update worked. thanks!
