### ISSUE TITLE
Review loading and display of metadata and EXIF data (as well as the boolean for 'has exif' and 'has audio'

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#279]
I've lost the thread on the current status of the metadata returned and displayed in the UI (or rather any obvious gaps/cleanup that needs to be done). 

Do you know of any places in the UI where we still have placeholders pulling (ass opposed to the real metadata from the DB)?

The EXIF data loading/display/and 'has exif' flags seem to be the most likely thing that isn't hooked up, but i'm not sure.

I think this task can encompass a few things:
1. A platform-wide review of known gaps in loading of meta/exif data. For these gaps they can either be filled as part of this task - or if some require deeper conversation can be broken out into separate tasks.

2. Review and update of https://github.com/benetech/VideoDeduplication/wiki/05.-Extracted-Metadata to ensure it is still up to date - but also add details about if.how those fields are mapped into UI elements.

**Comment by johnhbenetech** [comment]
FYI @fsbatista in case you know of any updates that need to be made to the wiki page

**Comment by fsbatista** [comment]
I'll review it. There are definitely a few updates that need to be made.
