### ISSUE TITLE
Extract actual exif attributes.

### ISSUE THREAD

**Issue by stepan-anokhin** [benetech/VideoDeduplication#313]
Currently file metadata is extracted by `mediainfo` which produces standard list of attributes retrieved from various sources depending on file format. `mediainfo` reads some limited metadata from exif when analysing [RIFF](https://en.wikipedia.org/wiki/Resource_Interchange_File_Format) files (e.g. `*.avi`). But for other file formats the exif data is not used. Also for riff files only a few exif attributes are retrieved. 

We need to implement a reliable way to extract exif data from video files.

**Comment by johnhbenetech** [comment]
Also remove current EXIF filter based on these changes
