### ISSUE TITLE
Template duplicate name collision no error display

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#333]
The template creation UI seems to prevent making two templates with the same name (this makes sense). However, there is no error message presented to the user, so it's unclear why the 'create' button isnt doing anything

**Comment by johnhbenetech** [comment]
@stepan-anokhin This doesnt seem to be working for me. The JS console throws an error now, but there in still no frontend feedback to the user

Steps to reproduce:
1. Create template with default icon and name
2. Attempt to create a second template with default icon and name
3. Hit Create button
4. No feedback provided to user

JS console output:
![image](https://user-images.githubusercontent.com/12927553/114604567-a429e500-9c5e-11eb-85b8-f22f2a575f30.png)


My expectation is that the following frontend actions would present an error message to the user:
1. Attempting to create a template with duplicate name
2. Attempting to edit existing template to the name of a different existing template

**Comment by stepan-anokhin** [comment]
Hmm. Wierd. The error should be displayed. I'll take a look.
