### ISSUE TITLE
Create a custom results view for template matches job.

### ISSUE THREAD

**Issue by stepan-anokhin** [benetech/VideoDeduplication#391]
On a task details page there should be a custom view displaying tempate matching results: list of matched template with a count of matched files for each template. By clicking on each template user should be navigated to the My Collection page with the corresponding matched files.

**Comment by johnhbenetech** [comment]
https://files.slack.com/files-pri/TDZJCEUH4-F02AXUN7LCC/image.png

can we afford these here
