### ISSUE TITLE
Research available datasets for object recognition benchmarking

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#44]
In order to separate the quality of our templates from the quality of the algorithm we should find a well established dataset used to assess industry object recognition approaches.

I'm imagining the available training data would be used to construct our template, and the testing data would be used as the "video" to be analyzed.

Based on our accuracy and precision we may choose to use this baseline  to evaluate new algorithmic approaches that demonstrate improved results.

**Comment by fsbatista** [comment]
Solved by our Template Matching benchmarking script. Scene detection is mentioned on #69
