### ISSUE TITLE
API documentation / swagger?

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#49]

**Comment by johnhbenetech** [comment]
@fsbatista Let us know when there is a version of the swagger code we can look at. Obviously this will be super important for @stepan-anokhin to get started

**Comment by fsbatista** [comment]
The code can be accessed here: 

https://app.swaggerhub.com/apis/fsbatista/video-deduplication/0.1

Let me know if you want to move into a "official" benetech swagger URL before we place it into the Readment
