### ISSUE TITLE
Establish beginning layout for main page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#61]
This task will involve getting the basic layout for the application established. As far as high-level structure, the application contains several pages, which each will contain several sub-pages. As this task is mainly about layout, there will be several sections of placeholder elements.

Some basic considerations:
* The font family is Roboto (primarily Medium and Bold)
* All fonts/images/frameworks/etc will need to be served locally as the application may be run offline
* Current icons are from https://ionicons.com/ but i dont really care what we use, so let me know if you have a better suggestion and I can pull from those
* All text should be referenced to strings files to allow for easy translations

Main mockup for the landing page:
![main landing page mockup](https://user-images.githubusercontent.com/12927553/87860087-24096580-c900-11ea-9092-aa05628d46e4.jpg)

When the hamburger menu is toggled, the sidebar page-nav shrinks:
![minimized side bar](https://user-images.githubusercontent.com/12927553/87860092-2c61a080-c900-11ea-86a1-d15554666468.jpg)

**Comment by johnhbenetech** [comment]
@stepan-anokhin I know the PR for this is still WIP, but I still wanted to point out some stuff to make sure we are on the same page. Feel free to break these out into separate issues if you want

* It seems the strings are hard coded ("winnow", "My Collection" etc.). We need to use something like react-localization package to manage these as separate strings. In this manner we will be able to easily drop in different translations with automatic substitution. It's important to have this established in the beginning since different languages will affect things like string length and often will point out CSS issues where the UI doesn't accurately handle the possibility of different languages having differnet length strings.

* The "winnow" title needs to be replaced with JusticeAI as in the mockup above. There will always be differences between the Invision mockup and the mockups in the Github Issues. As discussed the Invision mockup is more theoretical, so the Github Issues mockups should always take precedence over what is in Invision.

* I would expect this PR to also include the placeholders featured in the header above. The sub-pages as well as the upper-right section. I want this here so we can more quickly build out the functionality of these elements. Even just having the visual space and structure there will help ensure future commits don't unintentionally conflict with these elements.

Let me know if I'm misunderstanding anything or if these are known things you plan to remediate in this PR already

**Comment by stepan-anokhin** [comment]
Hi @johnhbenetech! Yup, this is exactly why PR is WIP at the moment. The plan is to
* Use Ionicons instead of material-ui icons
* Add navigation links at the page header
* Setup i18n

Thanks! I actually didn't know how to resolve discrepancies between Github issues & invision mockups and was going to ask you. :)

**Comment by stepan-anokhin** [comment]
@johnhbenetech please review #64
