### ISSUE TITLE
Initial hook up of search bar by filename

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#80]
As a preliminary step, the search bar should be usable to filter list/grid view by filename

* What do we think about "auto" search vs. search after submission? The big consideration here would be performance, so I'm open to suggestions.  If we do auto search, i'd probably recommend not launching the searches until at least 3 characters are entered and then a debounce of about 2 seconds

* once anything is entered, the magnifying glass icon should change to an 'x' icon which will clear/reset the entry

**Comment by johnhbenetech** [comment]
Hey @stepan-anokhin - i was unable to test this, I want to make sure I understand the state of the functionality.

What I tried
* set up and run required processing scripts
* confirm records show up in the interface
* attempt to search for known filenames

Result:
* Record list remain unchanged, no indication of filtering to find the entered text
* Magnifying icon doesnt change to clear/reset icon

**Comment by stepan-anokhin** [comment]
I've just tried it with current development branch and it works as expected (except for clear/reset icon - I overlooked that, will fix today).

The problem might be that docker-compose uses old images. If you're using gpu in your environment you can simply run
```
make stop
sudo docker-compose rm
sudo docker-compose build
make run
```
This will remove current containers, and rebuild images. I will add `make rebuild` shortcut for this purpose.

**Comment by stepan-anokhin** [comment]
@johnhbenetech Please #94.

The PR adds the following improvements: 
- Change search icon into clear-button when search-bar is not empty
- Force search (ignore delay) on `Enter` key press
- Clear search on `Escape` key press
- Handle fetch errors in file list and grid views.

Concerning fetch error handling. Previously on fetching error grid/list view kept trying to retrieve file-metadata from the server. Now a mock item will be displayed with error message and `Retry` link (see screen shots below)

Grid: 
![error_grid](https://user-images.githubusercontent.com/38860530/91293848-d87d8d80-e7c2-11ea-8698-025364cd1bb0.png)

List: 
![error_list](https://user-images.githubusercontent.com/38860530/91293858-dca9ab00-e7c2-11ea-8c17-2062be3fe6b3.png)

**Comment by johnhbenetech** [comment]
Awesome, thanks! I'm not sure why it wasn't working before since I always destroy all docker containers, images, and volumes before I rebuild. Oh well. One small tweak:

Can we make the search case insensitive?

**Comment by stepan-anokhin** [comment]
@johnhbenetech done. Please review #95 

Also added `maker rebuild` shortcut.
