### ISSUE TITLE
Schema review and recommendations for UUID proxy and Implementation 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#91]
In an effort to unblock some of the more substantial remaining features, we need to decide on a firm decision for the UUID approach we will use.

The scope of this task is to review any mismatches between the current schema and a UUID-based approach.

For each table in the schema, identify the need for additional data, joins, and the possibility of additional tables to represent core entities

**Comment by fsbatista** [comment]
Following up on our slack discussion:

Integer primary key
file-path
sha256
last-modified timestamp
Path+sha256 should be unique. This could be done by database constraint.
