### ISSUE TITLE
Add beginning layout for 'matches' page

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#93]
This will add a sub-selector within the single-video page to bring the user to a view of the matches to the video. The initial single-video view will be under the 'Video Details' sub selection. The number in 'XX Files Matches' will be dynamically updated.

We may want to link to this page from other places in the UI so it should also be available to directly visit via URI at some point. Initial mockup:

![matchesview](https://user-images.githubusercontent.com/12927553/91224128-405ea600-e6e7-11ea-8838-d5ba997228e0.jpg)

**Comment by stepan-anokhin** [comment]
@johnhbenetech please review #99 

Matches page layout: 

![2020-08-28-234221_1188x755_scrot](https://user-images.githubusercontent.com/38860530/91592333-99009e00-e988-11ea-9fd2-473c38382a1a.png)

Link from details page: 

![2020-08-28-234240_1194x764_scrot](https://user-images.githubusercontent.com/38860530/91592484-d7965880-e988-11ea-9f3f-fd359952042e.png)
