### ISSUE TITLE
Add dev/prod option in make flow for prebuilt images

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/VideoDeduplication#97]
During make flow, if user selects prebuilt option, ask if they want to pull the prod or dev images i.e. dockerhub tags of gpu vs. gpu-dev

**Comment by johnhbenetech** [comment]
Reopening for a few things:
@stepan-anokhin can you update the ReadMe docs to reflects any changes to the make flow

On my ubuntu machine when I'm presented with make option selectors (e.g. GPU vs CPU) i can use my arrow keys to move between options, but my enter key doesnt make the selection and move to the next step. The only way im able to make a selection oddly is by using the Esc key

**Comment by johnhbenetech** [comment]
Just a followup - Esc doesnt actually select - it just leaves those .env values blank

**Comment by stepan-anokhin** [comment]
@johnhbenetech could your please execute this script, press Enter, Space, arrows Up and Down and tell what the output was for each key? 

```bash
#!/usr/bin/env bash

echo "Press a button:"

while read -sN1 key; do
    read -sN1 -t 0.0001 k1
    read -sN1 -t 0.0001 k2
    read -sN1 -t 0.0001 k3
    key+="${k1}${k2}${k3}"

    # Enter or Space was pressed
    if [ -z "$key" ]; then
      echo "Enter or Space detected!"
    fi

    echo "Sequence: '$(xxd -pu <<< "${key}")'";
    echo
    echo "Press a button:"
done
```
